Fixes and additions to NL80211 interface
svinota/pyroute2 pull request #1168
Opened 2024-02-02 19:30 UTC by XDjackieXD

This PR adds parsing for the NL80211_RATE_INFO_ and NL80211_STA_BSS_PARAM_ enums and fixes parsing of the NL80211_STA_FLAG_ array.

2024-02-05 08:26 UTC, svinota commented
Thanks a lot, testing!

2024-02-07 10:36 UTC, svinota requested changes

2024-02-07 10:36 UTC, svinota commented on pyroute2/netlink/nl80211/__init__.py
> +                if mask & (1 << NL80211_STA_FLAG_AUTHORIZED):
Could it be better to move this shift to the flag definition like it is done for `NL80211_SCAN_FLAG_LOW_PRIORITY` etc?

2024-02-07 10:38 UTC, svinota commented
Please run also `make format` so `black` will fix the codestyle, but it's not a blocker, I can do it myself.

2024-02-07 10:48 UTC, XDjackieXD commented
Done

2024-02-07 12:03 UTC, svinota commented
LGTM, merging shortly

2024-02-07 12:13 UTC, svinota approved these changes

2024-02-07 12:34 UTC, merged

2024-02-07 12:34 UTC, svinota commented
Thanks for contribution!